### PR TITLE
Merged upstream changes from Klipper3d/klipper

### PR DESCRIPTION
**Pull request by benvanmierloo**
Compiled and tested on CR10s Pro with BLT upgrade. Everything seems to be ok.

### CODE REVIEW

**Comment by Ziip-dev** [comment]
Any update? It seems that Desuuuu custom klipper has been stalled for a while.
I have the same printer than you, so I might as well go back to mainstream klipper (hence loosing touchscreen but anyway) or use your fork :)

**Comment by benvanmierloo** [comment]
@Desuuuu , any interest in merging this in? 
Just checking if you are still maintaining this repo. If not, no problem, but then at least we know. 
Thanks!

**Comment by Desuuuu** [comment]
I'm not actively maintaining this repository so it would be hard for me to review these changes and test them tbh.

**Comment by benvanmierloo** [comment]
No problem, ill delete the pullrequest then.

**Comment by rai68** [comment]
i also tested with a e5plus, worked welled, too late i guess

**Pull request closed without merging**
