### PR TITLE
STM32 support

### PR DESCRIPTION
**Pull request by Desuuuu**
Adds support for STM32-based boards (SKR Mini E3 v2, ...).

### CODE REVIEW

**Comment by krzim** [comment]
> It would be great if you could give me more details like:
> 
>     * How you configured klipper
> 
>     * How you wired the touchscreen to the board

See the attached config file (added the `.txt` extension to appease GitHub):
[printer.cfg.txt](https://github.com/Desuuuu/klipper/files/6094253/printer.cfg.txt)

See the attached image for wiring:
wiring

**Comment by Desuuuu** [comment]
The build config looks correct to me.

If I go by the picture, you appear to have the serial connections swapped. RX on the screen should be connected to TX on the mainboard, and vice versa.

**Comment by krzim** [comment]
You are 100% correct. The 90 degree rotation of the LCD board tripped me up. I swapped them around and it looks like it works. I had flipped them once to troubleshoot things prior to reporting back to you but must have jammed the jumper alongside the pin and not on it or something.

I'll have to tweak the config since the bed doesn't retract far enough after homing to allow the bltouch to probe again. That makes the leveling feature error out immediately after homing is performed.

**Comment by krzim** [comment]
Just confirmed that it also works when UART2 is defined and you plug the screen into the TFT pins. I had a connector for that wired up already and plan to run it that way. 

I have another SKR Mini on the way since this one has a flaky X stepper driver. Once that gets here, I'll take a few photos, document the process, and submit a PR for others looking to do this. So far as I have found, this is the only way to use the stock screen, klipper, and the SKR Mini on an Ender 5 Plus.

**Comment by Bensal1999** [comment]
Dear folks, I need your help! I try to install Klipper on the stock Screen and mainboard on a Ender 6 and i have an error.(See picture) I am Not sure about the MCU settings I think there could be the problem located. I really appreciate any help. Thank you 
Error
MCU

**Comment by Desuuuu** [comment]
Thanks, this should be solved as of commit 278b1c0210f0bf17be74c799f2617432a8083a1c.

In the future, please open an issue in cases like this as it makes it easier to track problems.

**Pull request merged**
